FROM scratch

COPY judgeCore /home/gojudge/judgeCore/
COPY example.json /home/gojudge/judgeCore/
COPY complie    /home/gojudge/judgeCore/complie/
COPY judge/test /home/gojudge/judgeCore/judge/

WORKDIR /home/gojudge/judgeCore
